name: conveyance_apps
version: 0.1.0
publish_to: none
description: 'Conveyance (Inggris): Membawa atau menyampaikan informasi dengan jelas.'
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  google_fonts: ^6.1.0
  intl: ^0.19.0
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

