name: conveyance_apps
version: 0.1.0
publish_to: none
description: "Conveyance (Inggris): Membawa atau menyampaikan informasi dengan jelas."
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
